springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
server:
  forward-headers-strategy: framework
# application.yml (both apps)
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true     # enables /actuator/health/liveness & /readiness
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
