apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: patient-ms
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: auth-service
          image: neethika1304/auth-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4005
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres.patient-ms.svc.cluster.local:5432/authdb
            - name: SPRING_DATASOURCE_USERNAME
              value: pm_user
            - name: SPRING_DATASOURCE_PASSWORD
              value: pm_pass

          # Wait for Spring Boot to be fully started before liveness kicks in
          startupProbe:
            tcpSocket: { port: 4005 }
            failureThreshold: 60
            periodSeconds: 3
            timeoutSeconds: 2

          readinessProbe:
            tcpSocket: { port: 4005 }
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 6

          livenessProbe:
            tcpSocket: { port: 4005 }
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6

          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: patient-ms
spec:
  selector:
    app: auth-service
  ports:
    - port: 4005
      targetPort: 4005
      protocol: TCP
      name: http
