apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: patient-ms
  labels: { app: auth-service }
spec:
  replicas: 1
  selector:
    matchLabels: { app: auth-service }
  template:
    metadata:
      labels: { app: auth-service }
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: auth-service
          # TIP: pin a version tag instead of :latest (e.g., :1.0.0)
          image: neethika1304/auth-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4005
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres.patient-ms.svc.cluster.local:5432/authdb
            - name: SPRING_DATASOURCE_USERNAME
              value: pm_user
            - name: SPRING_DATASOURCE_PASSWORD
              value: pm_pass
            # JVM sizing that behaves well in containers
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:MaxRAMPercentage=75 -XX:InitialRAMPercentage=50"

          # Probes → same style as analytics-service, on port 4005
          startupProbe:
            httpGet: { path: /actuator/health/liveness, port: 4005 }
            failureThreshold: 30
            periodSeconds: 3
            timeoutSeconds: 2
          readinessProbe:
            httpGet: { path: /actuator/health/readiness, port: 4005 }
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            httpGet: { path: /actuator/health/liveness, port: 4005 }
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: patient-ms
spec:
  selector: { app: auth-service }
  ports:
    - name: http
      port: 4005
      targetPort: 4005
      protocol: TCP
