apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: patient-ms
  labels: { app: analytics-service }
spec:
  replicas: 1
  selector:
    matchLabels: { app: analytics-service }
  template:
    metadata:
      labels: { app: analytics-service }
    spec:
      containers:
        - name: analytics-service
          image: neethika1304/analytics-service:latest
          imagePullPolicy: Always
          # If your analytics-service does NOT expose HTTP, you can drop ports/probes.
          ports:
            - containerPort: 4003
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka.patient-ms.svc.cluster.local:9092
          readinessProbe:
            tcpSocket: { port: 4003 }
            initialDelaySeconds: 10
          livenessProbe:
            tcpSocket: { port: 4003 }
            initialDelaySeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: patient-ms
spec:
  selector: { app: analytics-service }
  ports:
    - port: 4003
      targetPort: 4003
